//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Purchase_Id { get; set; }
        public string CustomerTel { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> AtStore { get; set; }
        public Nullable<decimal> MoneyTaken { get; set; }
        public Nullable<decimal> MoneyExchange { get; set; }
        public string DeliveryAdress { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Ship { get; set; }
        public Nullable<decimal> MoneyWillGet { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual Purchase Purchase1 { get; set; }
        public virtual Purchase Purchase2 { get; set; }
    }
}
